title: An Dabe
description: Seize the day, gather ye rosebuds while ye may.
baseurl: "wesson2775.github.io"
url: "Blog"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 5
paginate_path: "/page/:num/"
collections:
  docs:
    output: true
    permalink: /docs/:name
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: post

