title: An Dabe
description: Seize the day, gather ye rosebuds while ye may.
baseurl: "/Blog"
url: "https://wesson2775.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
collections:
  docs:
    output: true
    permalink: /docs/:name
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: post