title: An Dabe
description: "seize the day, gather ye rosebuds while yemay."
baseurl: "wesson2775.github.io"
url: "blog"
timezone: Asia/Shanghai
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
    values:
      layout: default