title: 我的流体博客
description: 记录生活与思考
baseurl: "/blog" # 如果部署在子目录，如 /your-repo-name，需修改
url: "https://wesson2775.github.io"
permalink: /blogs/:year/:month/:day/:title/

collections:
  fragments:
    output: true
    permalink: /fragments/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "fragments"
    values:
      layout: "fragment"