title: 我的流体博客
description: 记录生活与思考
baseurl: "/blog" # 你的子目录
url: "https://wesson2775.github.io" # 你的 GitHub Pages 主域名
permalink: /blogs/:year/:month/:day/:title/

collections:
  fragments:
    output: true
    permalink: /fragments/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "fragments"
    values:
      layout: "fragment"