title: An Dabe
description: Seize the day, gather ye rosebuds while ye may.
baseurl: "/Blog"
url: "https://wesson2775.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# _config.yml 必须包含以下配置
collections:
  docs:
    output: true
    permalink: /:path/
    title: Docs

defaults:
  - scope:
      path: "_docs"  # 明确指定路径
      type: docs
    values:
      layout: post
# 替换原来的分页配置
pagination:
  enabled: true
  collection: 'docs'  # 指定对docs集合分页
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - 第:num页'