title: An Dabe
description: Seize the day, gather ye rosebuds while ye may.
author: Dayu
email: your-email@example.com
baseurl: "/Blog"
url: "https://wesson2775.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
search:
  enabled: true
collections:
  fragments:
    output: true
    permalink: /fragments/:path/
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      permalink: /posts/:slug/
  - scope:
      path: "_fragments"
      type: fragments
    values:
      layout: fragments
      collection: fragments
  - scope:
      path: "search.html"
      type: pages
    values:
      layout: default
  - scope:
      path: "fragments.html"
      type: pages
    values:
      layout: default
posts:
  filename_date: false