title: An Dabe
description: Seize the day, gather ye rosebuds while ye may.
baseurl: "/Blog"
url: "https://wesson2775.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

collections:
  fragments:
    output: true
    permalink: /fragments/:path/

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
  - scope:
      path: "_fragments"
      type: fragments
    values:
      layout: fragments

# 分页配置
paginate: 5
paginate_path: "/page/:num/"