title: An Dabe
description: Seize the day, gather ye rosebuds while ye may.
baseurl: "/Blog"
url: "https://wesson2775.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
# _config.yml 必须包含以下配置
collections:
  docs:
    output: true
    permalink: /:path/
    title: Docs

defaults:
  - scope:
      path: "_docs"  # 明确指定路径
      type: docs
    values:
      layout: post
# 分页配置
pagination:
  enabled: true
  collection: docs       # 对哪个集合分页
  per_page: 5           # 每页文章数
  permalink: "/page/:num/" # 分页路径格式
  limit: 0              # 0表示无限制
  sort_field: "date"    # 按日期排序
  sort_reverse: true    # 倒序排列
  trail: 
    before: 2           # 当前页前显示2个页码
    after: 2            # 当前页后显示2个页码