title: An Dabee
description: Seize the day, gather ye rosebuds while ye may.
baseurl: "/Blog"
url: "https://wesson2775.github.io"
author: Dayu
start_year: 2021
license: CC BY-NC-ND 4.0
email: your-email@example.com
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

search:
  enabled: true

collections:
  fragments:
    output: false
    permalink: /fragments/:path/

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      permalink: /posts/:slug/
  - scope:
      path: "_fragments"
      type: fragments
    values:
      layout: fragments

paginate: 5
paginate_path: "/page/:num/"

posts:
  filename_date: false